# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import classifier_pb2 as classifier__pb2


class ImageClassifierStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyImage = channel.unary_unary(
                '/classifier.ImageClassifier/ClassifyImage',
                request_serializer=classifier__pb2.ImageRequest.SerializeToString,
                response_deserializer=classifier__pb2.ImageReply.FromString,
                )


class ImageClassifierServicer(object):
    """Service definition
    """

    def ClassifyImage(self, request, context):
        """Unary RPC: send one image, get one prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyImage,
                    request_deserializer=classifier__pb2.ImageRequest.FromString,
                    response_serializer=classifier__pb2.ImageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'classifier.ImageClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageClassifier(object):
    """Service definition
    """

    @staticmethod
    def ClassifyImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/classifier.ImageClassifier/ClassifyImage',
            classifier__pb2.ImageRequest.SerializeToString,
            classifier__pb2.ImageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
