# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classifier.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63lassifier.proto\x12\nclassifier\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"/\n\nImageReply\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32T\n\x0fImageClassifier\x12\x41\n\rClassifyImage\x12\x18.classifier.ImageRequest\x1a\x16.classifier.ImageReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classifier_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=32
  _globals['_IMAGEREQUEST']._serialized_end=66
  _globals['_IMAGEREPLY']._serialized_start=68
  _globals['_IMAGEREPLY']._serialized_end=115
  _globals['_IMAGECLASSIFIER']._serialized_start=117
  _globals['_IMAGECLASSIFIER']._serialized_end=201
# @@protoc_insertion_point(module_scope)
